# Generated by Django 4.2.20 on 2025-07-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_envoye', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='attente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('commentaire', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
