# Generated by Django 4.2.20 on 2025-07-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagecontact',
            old_name='date_envoye',
            new_name='date_envoi',
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='statut',
            field=models.CharField(default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='sujet',
            field=models.CharField(max_length=255),
        ),
    ]
