# Generated by Django 4.2.20 on 2025-08-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_date_envoye_messagecontact_date_envoi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontact',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='type_demande',
            field=models.CharField(choices=[('contact', 'Message de contact'), ('stage', 'Demande de stage'), ('cv', 'Envoi de CV')], default='contact', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='sujet',
            field=models.CharField(max_length=200),
        ),
    ]
