# Generated by Django 4.2.20 on 2025-08-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_messagecontact_cv_messagecontact_type_demande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoin',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
