# Generated by Django 4.2.20 on 2025-08-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontact',
            name='reponse_admin',
            field=models.TextField(blank=True, null=True),
        ),
    ]
