# Generated by Django 4.2.20 on 2025-08-22 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Acceptée', 'Acceptée'), ('Rejetée', 'Rejetée')], default='En attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('corps', models.TextField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Répondu', 'Répondu'), ('Rejeté', 'Rejeté')], default='En attente', max_length=20)),
                ('reponse_admin', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
