# Generated by Django 4.2.20 on 2025-08-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='contenu',
        ),
        migrations.AddField(
            model_name='message',
            name='sujet',
            field=models.CharField(default='Sans sujet', max_length=200),
        ),
    ]
