# Generated by Django 4.2.20 on 2025-08-24 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_rename_content_message_contenu_message_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageclient',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messageclient_as_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageclient',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messageclient_as_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messageclient',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messageclient_as_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
