# Generated by Django 4.2.20 on 2025-08-26 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_messageclient_receiver_messageclient_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoin',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='temoin',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
