# Generated by Django 4.2.20 on 2025-08-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_temoin_date_alter_temoin_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoin',
            name='note',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
