# Generated by Django 4.2.20 on 2025-08-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_reponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageClient',
        ),
    ]
