# Generated by Django 4.2.20 on 2025-08-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_profile_avatar_alter_reponse_message_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
