# Generated by Django 4.2.20 on 2025-09-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_article_auteur_article_categorie_article_vues'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='objet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
