# Generated by Django 4.2.20 on 2025-09-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_formation_objet'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='capacite',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='formation',
            name='duree',
            field=models.CharField(default='1 jour', max_length=50),
        ),
        migrations.AddField(
            model_name='formation',
            name='lieu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
