# Generated by Django 4.2.20 on 2025-09-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_inscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='horaire',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='mode',
            field=models.CharField(choices=[('en_ligne', 'En ligne'), ('presentiel', 'Présentiel')], default='presentiel', max_length=10),
        ),
    ]
