# Generated by Django 4.2.20 on 2025-09-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_formation_horaire_formation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='horaire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
