# Generated by Django 4.2.20 on 2025-09-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_formation_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='lieu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
