# Generated by Django 4.2.20 on 2025-09-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_formation_lieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='mode',
            field=models.CharField(choices=[('en_ligne', 'En ligne'), ('presentiel', 'Présentiel')], default='presentiel et en ligne', max_length=10),
        ),
    ]
