# Generated by Django 4.2.20 on 2025-09-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_formation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='trimestre',
            field=models.CharField(blank=True, choices=[('1er', '1er trimestre '), ('2ème', '2ème trimestre'), ('3ème', '3ème trimestre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='duree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='horaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='mode',
            field=models.CharField(choices=[('en_ligne', 'En ligne'), ('presentiel', 'Présentiel'), ('mixte', 'Présentiel et En ligne')], default='presentiel et en ligne', max_length=10),
        ),
    ]
