# Generated by Django 4.2.20 on 2025-09-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_formation_trimestre_alter_formation_duree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='trimestre',
            field=models.CharField(blank=True, choices=[('1er', '1er trimestre : septembre - novembre'), ('2eme', '2ème trimestre : décembre - février'), ('3eme', '3ème trimestre : mars - mai'), ('4eme', '4ème trimestre : juin - août'), ('mixte', '1er trimestre : septembre - novembre, 2ème trimestre : décembre - février, 3ème trimestre : mars - mai, 4ème trimestre : juin - août')], max_length=50, null=True),
        ),
    ]
