# Generated by Django 4.2.20 on 2025-09-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_formation_trimestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='mode',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('mixte', 'Mixte')], default='mixte', max_length=20),
        ),
    ]
