# Generated by Django 4.2.20 on 2025-09-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_inscription_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='mode',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('mixte', 'Mixte')], default='presentiel', max_length=20),
        ),
    ]
