# Generated by Django 4.2.20 on 2025-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_inscription_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='trimestre',
            field=models.CharField(blank=True, choices=[('1er', '1er'), ('2eme', '2ème'), ('3eme', '3ème'), ('4eme', '4ème')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='capacite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formation',
            name='mode',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('mixte', 'Présentiel et En ligne')], default='mixte', max_length=15),
        ),
        migrations.AlterField(
            model_name='formation',
            name='trimestre',
            field=models.CharField(choices=[('1er', '1er trimestre : septembre - novembre'), ('2eme', '2ème trimestre : décembre - février'), ('3eme', '3ème trimestre : mars - mai'), ('4eme', '4ème trimestre : juin - août'), ('mixte', 'Tous les trimestres')], default='mixte', max_length=10),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='mode',
            field=models.CharField(blank=True, choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne')], max_length=20, null=True),
        ),
    ]
