# Generated by Django 4.2.20 on 2025-09-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_inscription_trimestre_alter_formation_capacite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='mode',
            field=models.CharField(choices=[('présentiel', 'Présentiel'), ('en_ligne', 'En ligne')], default='présentiel', max_length=50),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='trimestre',
            field=models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], default='T1', max_length=50),
        ),
    ]
