# Generated by Django 4.2.20 on 2025-09-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_inscription_mode_alter_inscription_trimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='mode',
            field=models.CharField(choices=[('présentiel', 'Présentiel'), ('en_ligne', 'En ligne')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='trimestre',
            field=models.CharField(choices=[('1er', '1er trimestre : septembre - novembre'), ('2eme', '2ème trimestre : décembre - février'), ('3eme', '3ème trimestre : mars - mai'), ('4eme', '4ème trimestre : juin - août')], max_length=10),
        ),
    ]
