# Generated by Django 4.2.20 on 2025-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_inscription_mode_alter_inscription_trimestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('carte', 'Carte bancaire'), ('paypal', 'PayPal'), ('especes', 'Espèces'), ('virement', 'Virement bancaire')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='paiement_effectue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validée'), ('refuse', 'Refusée')], default='attente', max_length=20),
        ),
    ]
