# Generated by Django 4.2.20 on 2025-09-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_inscription_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='paiement_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
