# Generated by Django 4.2.20 on 2025-09-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_inscription_paiement_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(default='En attente', max_length=50),
        ),
    ]
