# Generated by Django 4.2.20 on 2025-09-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_inscription_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='paiement_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
