# Generated by Django 4.2.20 on 2025-09-13 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_inscription_paiement_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('statut', models.CharField(default='en attente', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='home.inscription')),
            ],
        ),
    ]
