# Generated by Django 4.2.20 on 2025-09-13 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='service',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.inscription'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(default='en attente', max_length=50),
        ),
    ]
