# Generated by Django 4.2.20 on 2025-09-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_paiement_adresse_paiement_details_paiement_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
